routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/products', [App\Http\Controllers\HomeController::class, 'products'])->name('products');
Route::get('/categories/{category}/products', [App\Http\Controllers\HomeController::class, 'categoryShow'])->name('categories.products');
Route::get('/apply', [App\Http\Controllers\HomeController::class, 'apply'])->name('apply');
Route::post('/apply', [App\Http\Controllers\HomeController::class, 'applySubmit']);
Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact'])->name('contact');
Route::post('/contact', [App\Http\Controllers\HomeController::class, 'contactSubmit']);

Auth::routes(['register' => false]);

Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {


    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('dashboard');

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('types', App\Http\Controllers\Admin\TypeController::class);
    Route::get('products/export', [\App\Http\Controllers\Admin\ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [\App\Http\Controllers\Admin\ProductController::class, 'import'])->name('products.import');
    Route::resource('products', App\Http\Controllers\Admin\ProductController::class);
    Route::resource('applications', App\Http\Controllers\Admin\ApplicationFormController::class);
    Route::resource('documents', App\Http\Controllers\Admin\DocumentController::class);

});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}"></script>

    </head>
    <body class="">
        @include('admin.layouts.navigation')
        <div class="container-fluid">

            <!-- Page Heading -->
            {{-- <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header> --}}

            <!-- Page Content -->
            <main>
                <div id="wrapper" class="toggled">
                @include('admin.layouts.sidebar')
                    <div id="content" class="p-3" style="margin-left: 80px">
                        @include('flash::message')
                        {{ $slot }}
                    </div>
                </div>
            </main>
        </div>
        @yield('footer')
    </body>
</html>

resources/views/admin/layouts/navigation.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-admin-site">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarSupportedContent">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false" style="color: black">
                {{ Auth::user()->name }}
            </a>
            <ul class="dropdown-menu dropdown-menu-right mr-5" aria-labelledby="navbarDropdown">
              <li class="dropdown-item"><a href="{{ route('logout') }}" class="text-left pl-3" style="font-size: 18px;">Log Out</a></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/layouts/sidebar.blade.php
<nav id="sidebar" class="active">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand d-flex">
                <a href="#" id="menu-toggle"><i class="fa fa-bars" style="margin-right: 50px" aria-hidden="true"></i></a>
            </li>
            <li class="mt-4">
                <a href="{{ route('admin.dashboard') }}"><i class="fas fa-home" aria-hidden="true" style="margin-right: 50px"></i><span>Dashboard</span></a>
            </li>
            <li>
                <a href="#inventory" class="sidebar-toggle" data-toggle="collapse" aria-expanded="false"><i class="fas fa-shopping-cart" aria-hidden="true" style="margin-right: 50px"></i><span>Products</span></a>
                <div id="inventory" class="collapse sidebar-submenu">
                    <a href="{{ route('admin.products.index') }}">
                        <span class="menu-collapsed">Products</span>
                    </a>
                    <a href="{{ route('admin.categories.index') }}">
                        <span class="menu-collapsed">Categories</span>
                    </a>
                    <a href="{{ route('admin.types.index') }}">
                        <span class="menu-collapsed">Types</span>
                    </a>
                </div>
            </li>
            <li>
                <a href="{{ route('admin.applications.index') }}"><i class="fas fa-file-alt" aria-hidden="true" style="margin-right: 50px"></i><span>Application Management</span></a>
            </li>
            <li>
                <a href="{{ route('admin.documents.index') }}"><i class="fas fa-folder" aria-hidden="true" style="margin-right: 50px"></i><span>File Management</span></a>
            </li>
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->
</nav>