routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/products', [App\Http\Controllers\HomeController::class, 'products'])->name('products');
Route::get('/categories/{category}/products', [App\Http\Controllers\HomeController::class, 'categoryShow'])->name('categories.products');
Route::get('/apply', [App\Http\Controllers\HomeController::class, 'apply'])->name('apply');
Route::post('/apply', [App\Http\Controllers\HomeController::class, 'applySubmit']);
Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact'])->name('contact');
Route::post('/contact', [App\Http\Controllers\HomeController::class, 'contactSubmit']);

Auth::routes(['register' => false]);

Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {


    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('dashboard');

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('types', App\Http\Controllers\Admin\TypeController::class);
    Route::get('products/export', [\App\Http\Controllers\Admin\ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [\App\Http\Controllers\Admin\ProductController::class, 'import'])->name('products.import');
    Route::resource('products', App\Http\Controllers\Admin\ProductController::class);
    Route::resource('applications', App\Http\Controllers\Admin\ApplicationFormController::class);
    Route::resource('documents', App\Http\Controllers\Admin\DocumentController::class);

});

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name', 'company', 'brand', 'model', 'size', 'material', 'country', 'email', 'office_number',
        'expiry_date', 'category_id', 'application_form_id', 'cert_no',
    ];

    protected $casts = [
        'model' => 'array'
    ];

    public function setExpiryDateAttribute($value)
    {
        if (!empty($value)) {
            $this->attributes['expiry_date'] = Carbon::createFromFormat('d-m-Y', $value)->format('Y-m-d');
        } else {
            $this->attributes['expiry_date'] = null;
        }
    }

    public function getExpiryDateAttribute($value)
    {
        if (!empty($value)) {
            return Carbon::parse($value)->format('d-m-Y');
        }
        return null;
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function application()
    {
        return $this->belongsTo(ApplicationForm::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\ProductExport;
use App\Http\Controllers\Controller;
use App\Imports\DeclarationImport;
use App\Imports\ProductImport;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $products = Product::orderBy("created_at", "desc");
        $query = $request->query("q");

        if ($query) {
            $products = $products->where("company", "like", "%" . $query . "%")->orWhere("model", "like", "%" . $query . "%")->orWhere("brand", "like", "%" . $query . "%")->orWhere("name", "like", "%" . $query . "%")->orWhereHas('category', function ($subq) use ($query) {
                $subq->where('name', 'like', '%' . $query . '%');
            });
        }

        $products = $products->paginate(10);
        return view('admin.products.index', compact('query', 'products'));
    }

    public function create()
    {
        $categories = Category::where('type', 1)->get();
        return view('admin.products.form', compact('categories'));
    }

    public function store(Request $request)
    {
        $input = $request->input();
        $models = [];
        if (!empty($input['models'])) {
            $model = explode(',', $input['models']);
            foreach ($model as $i) {
                $models[] = ['name' => trim($i)];
            }
        }
        $input['model'] = $models;
        Product::create($input);
        flash()->success('Successfully created the product.');
        return redirect(route('admin.products.index'));
    }

    public function edit(Product $product)
    {
        $categories = Category::where('type', 1)->get();
        return view('admin.products.form', compact('product', 'categories'));
    }

    public function update(Request $request, Product $product)
    {
        $input = $request->input();
        $models = [];
        if (!empty($input['models'])) {
            $model = explode(',', $input['models']);
            foreach ($model as $i) {
                $models[] = ['name' => trim($i)];
            }
        }
        $input['model'] = $models;
        $product->update($input);
        flash()->success('Successfully updated the product.');
        return redirect(route('admin.products.index'));
    }

    public function import(Request $request)
    {
        $import = new ProductImport();
        Excel::import($import, $request->import_file);
        if (!empty($import->errors)) {
            foreach ($import->errors as $error) {
                flash()->error($error);
            }
        }
        flash()->success('Successfully imported the file.');
        return back();
    }

    public function export(Request $request)
    {
        $export = new ProductExport();
        return Excel::download($export, 'products.xlsx');
    }

    public function destroy(Product $product)
    {
        $product->delete();
        flash()->success('Successfully imported the file.');
        return redirect(route('admin.products.index'));
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('admin.layouts.app');
    }
}

resources/views/admin/products/form.blade.php
<x-app-layout>
    <div class="container-fluid" id="app">
        {{-- header --}}
        <div class="d-flex justify-content-between p-3" style="border-bottom-width:2px">
            <div>
                <h4 class="font-weight-bold"> @if (!isset($product))Create @else Edit @endif Product</h4>
                <h6>@if (!isset($product))Create @else Edit @endif a new product</h6>
            </div>
            <div class="mt-3 mb-3" style="border-top-width:3px">
                <div>
                    @if (!empty($product))
                    <form action="{{ route('admin.products.destroy', [$product->getRouteKey()]) }}" method="POST" class="d-inline-block mr-3">
                        @method('DELETE')
                        @csrf
                        <div class="text-right">
                            <button class="btn btn-danger px-4" type="submit" onclick="return confirm('Are you sure you want to delete? This will delete all the types related to this product. You cannot revert this.')">
                                Delete
                            </button>
                        </div>
                    </form>
                    @endif
                    <a href="{{ route('admin.products.index') }}" class="btn btn-alt px-5">Back</a>
                </div>
            </div>
        </div>

        {{--Form --}}
        <div class="card shadow bg-white mt-4">
        @if(isset($product))
            <form action="{{ route('admin.products.update', $product->id) }}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
        @else
            <form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
        @endif

            @csrf

            @if(session()->has('message'))
            <div class="alert alert-success">
                {{ session()->get('message') }}
            </div>
            @endif

                <div class="card-header bg-theme rounded-top">
                    <div class="ms-4 mt-2 mb-2">Product Information</div>
                </div>

                <div class="card-body">
                    <div class="container mt-4">
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Type</label>
                            <div class="col-md-8">
                                <select name="category_id" class="form-control" required>
                                    @foreach ($categories as $categoryTwo)
                                        <option value="{{ $categoryTwo->id }}" {{ !empty($product) ? ($product->category_id == $categoryTwo->id ? 'selected' : '') : '' }}>{{ $categoryTwo->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="text-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Company</label>
                            <div class="col-md-8">
                                <input type="text" name="company" value="{{ !empty(old()) ? old('company') : (isset($product) ? $product->company : '') }}" class="form-control" required />
                                @if($errors->has('company'))
                                    <div class="text-danger">{{ $errors->first('company') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Name</label>
                            <div class="col-md-8">
                                <input type="text" name="name" value="{{ !empty(old()) ? old('name') : (isset($product) ? $product->name : '') }}" class="form-control" required />
                                @if($errors->has('name'))
                                    <div class="text-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Certificate No</label>
                            <div class="col-md-8">
                                <input type="text" name="cert_no" value="{{ !empty(old()) ? old('cert_no') : (isset($product) ? $product->cert_no : '') }}" class="form-control" required />
                                @if($errors->has('cert_no'))
                                    <div class="text-danger">{{ $errors->first('cert_no') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Brand</label>
                            <div class="col-md-8">
                                <input type="text" name="brand" value="{{ !empty(old()) ? old('brand') : (isset($product) ? $product->brand : '') }}" class="form-control" required />
                                @if($errors->has('brand'))
                                    <div class="text-danger">{{ $errors->first('brand') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Country</label>
                            <div class="col-md-8">
                                <input type="text" name="country" value="{{ !empty(old()) ? old('country') : (isset($product) ? $product->country : '') }}" class="form-control" required />
                                @if($errors->has('country'))
                                    <div class="text-danger">{{ $errors->first('country') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Size</label>
                            <div class="col-md-8">
                                <input type="text" name="size" value="{{ !empty(old()) ? old('size') : (isset($product) ? $product->size : '') }}" class="form-control" />
                                @if($errors->has('size'))
                                    <div class="text-danger">{{ $errors->first('size') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Model</label>
                            <div class="col-md-8">
                                <input type="text" name="models" value="{{ implode(', ', collect($product->model ?? [])->pluck('name')->toArray()) }}" class="form-control" />
                                @if($errors->has('size'))
                                    <div class="text-danger">{{ $errors->first('size') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Email</label>
                            <div class="col-md-8">
                                <input type="email" name="email" value="{{ !empty(old()) ? old('email') : (isset($product) ? $product->email : '') }}" class="form-control" required />
                                @if($errors->has('email'))
                                    <div class="text-danger">{{ $errors->first('email') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-4 mt-4">
                            <label class="col-md-4 text-right col-form-label">Phone No</label>
                            <div class="col-md-8">
                                <input type="text" name="office_number" value="{{ !empty(old()) ? old('office_number') : (isset($product) ? $product->office_number : '') }}" class="form-control" required />
                                @if($errors->has('office_number'))
                                    <div class="text-danger">{{ $errors->first('office_number') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-4 mb-5">
                    <button class="btn btn-primary px-5">{{ isset($product) ? 'Update' : 'Create' }}</button>
                </div>
            </form>
        </div>
    </div>

</x-app-layout>

resources/views/admin/products/index.blade.php
<x-app-layout>
    <div class="container-fluid" id="app">

        @if(session()->has('message'))
        <div class="alert alert-danger">
            {{ session()->get('message') }}
        </div>
        @endif

        {{-- header --}}
        <div class="row justify-content-between align-items-center w-100 border-bottom pb-4">
            <div class="col-6">
                <h5>Products List</h5>
            </div>
            <div class="col-6 text-right">
                <form method="POST" action="{{ route('admin.products.import') }}" enctype="multipart/form-data">
                    @csrf
                    <input name="import_file" type="file" accept=".xlsx" style="display: none" id="file-upload" onchange="this.form.submit()" />
                </form>
                <button class="btn btn-primary px-5 me-3" type="button" onclick="$('#file-upload').click()">Import</button>
                <a class="btn btn-secondary text-white px-5" href="{{ route('admin.products.export') }}" data-bs-toggle="modal">Export</a>
                <a href="{{ route('admin.products.create') }}" class="btn btn-identity px-5">Create</a>
            </div>
        </div>
        {{-- search and button --}}
        <div class="row my-4">
            <div class="col-lg-4 col-md-6">
                <form id="frmSearch" action="{{ route('admin.products.index') }}" method="GET">
                    <div class="w-100">
                        <input type="text" name="q" placeholder="Search in the current filter" value="{{ $query }}" class="form-control d-inline-block" style="width: calc(100% - 100px); background: #ececec">
                        <i class="fa fa-search" onclick="document.getElementById('frmSearch').submit()" style="cursor: pointer;"></i>
                    </div>
                </form>
            </div>
        </div>

        {{-- index table --}}
        <div class="row mt-2">
            <div class="table-responsive">
                <table class="table table-rounded table-striped w-100 mt-4">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Company</th>
                            <th>Name</th>
                            <th>Brand</th>
                            <th>Model</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($products as $product)
                            <tr>
                                <td>{{ $product->category ? $product->category->name : '-' }}</td>
                                <td>{{ $product->company }}</td>
                                <td>{{ $product->name }}</td>
                                <td>{{ $product->brand }}</td>
                                <td>{{ implode(', ', collect($product->model ?? [])->pluck('name')->toArray()) }}</td>
                                <td class="d-flex">
                                    <a class="btn-link btn-sm" href="{{ route('admin.products.edit', [$product->getRouteKey()]) }}">Edit</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="text-center bg-white">There are no products.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        {{ $products->links() }}
    </div>
</x-app-layout>