routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::get('/about', function () {
    return view('about');
})->name('about');
Route::get('/products', [App\Http\Controllers\HomeController::class, 'products'])->name('products');
Route::get('/categories/{category}/products', [App\Http\Controllers\HomeController::class, 'categoryShow'])->name('categories.products');
Route::get('/apply', [App\Http\Controllers\HomeController::class, 'apply'])->name('apply');
Route::post('/apply', [App\Http\Controllers\HomeController::class, 'applySubmit']);
Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact'])->name('contact');
Route::post('/contact', [App\Http\Controllers\HomeController::class, 'contactSubmit']);

Auth::routes(['register' => false]);

Route::get('logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth']], function() {


    Route::get('/', [\App\Http\Controllers\HomeController::class, 'admin'])->name('dashboard');

    Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('types', App\Http\Controllers\Admin\TypeController::class);
    Route::get('products/export', [\App\Http\Controllers\Admin\ProductController::class, 'export'])->name('products.export');
    Route::post('products/import', [\App\Http\Controllers\Admin\ProductController::class, 'import'])->name('products.import');
    Route::resource('products', App\Http\Controllers\Admin\ProductController::class);
    Route::resource('applications', App\Http\Controllers\Admin\ApplicationFormController::class);
    Route::resource('documents', App\Http\Controllers\Admin\DocumentController::class);

});

app/Http/Controllers/Admin/TypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class TypeController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $categories = Category::where('type', 1);
        $query = $request->query("q");

        if ($query) {
            $categories = $categories->where("name", "like", "%" . $query . "%");
        }

        $categories = $categories->orderBy("created_at", "desc")->paginate(10);
        return view('admin.types.index', compact('query', 'categories'));
    }

    public function create()
    {
        $categories = Category::where('type', 0)->get();
        return view('admin.types.form', compact('categories'));
    }

    public function store(Request $request)
    {
        $input = $request->input();
        Category::create($input);
        flash()->success('Successfully created the product type.');
        return redirect(route('admin.types.index'));
    }

    public function edit(Category $type)
    {
        $categories = Category::where('type', 0)->get();
        $category = $type;
        return view('admin.types.form', compact('category', 'categories'));
    }

    public function update(Request $request, Category $type)
    {
        $category = $type;
        $category->update($request->input());
        flash()->success('Successfully updated the product type.');
        return redirect(route('admin.types.index'));
    }

    public function destroy(Category $type)
    {
        $type->delete();
        flash()->success('Successfully deleted the type');
        return redirect(route('admin.types.index'));
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('admin.layouts.app');
    }
}

resources/views/admin/types/form.blade.php
<x-app-layout>
    <div class="container-fluid" id="app">
        {{-- header --}}
        <div class="d-flex justify-content-between p-3" style="border-bottom-width:2px">
            <div>
                <h4 class="font-weight-bold"> @if (!isset($category))Create @else Edit @endif Product Type</h4>
                <h6>@if (!isset($category))Create @else Edit @endif a new product type</h6>
            </div>
            <div class="mt-3 mb-3" style="border-top-width:3px">
                <div>
                    @if (!empty($category))
                        <form action="{{ route('admin.types.destroy', [$category->getRouteKey()]) }}" method="POST" class="d-inline-block mr-3">
                            @method('DELETE')
                            @csrf
                            <div class="text-right">
                                <button class="btn btn-danger px-4" type="submit" onclick="return confirm('Are you sure you want to delete? This will delete all the types related to this category. You cannot revert this.')">
                                    Delete
                                </button>
                            </div>
                        </form>
                    @endif
                    <a href="{{ route('admin.types.index') }}" class="btn btn-alt px-5">Back</a>
                </div>
            </div>
        </div>

        {{--Form --}}
        <div class="card shadow bg-white mt-4">
            @if(isset($category))
                <form action="{{ route('admin.types.update', $category->getRouteKey()) }}" method="POST" enctype="multipart/form-data">
                @method('PATCH')
            @else
                <form action="{{ route('admin.types.store') }}" method="POST" enctype="multipart/form-data">
            @endif

            @csrf

                <div class="card-header bg-theme rounded-top">
                    <div class="ms-4 mt-2 mb-2">Product Type Information</div>
                </div>

                <div class="card-body">
                    <div class="container mt-5">
                        <div class="form-group row mb-5 mt-5">
                            <label class="col-md-5 text-right col-form-label">Type</label>
                            <div class="col-md-5">
                                <input type="text" name="name" value="{{ !empty(old()) ? old('name') : (isset($category) ? $category->name : '') }}" class="form-control" required />
                                @if($errors->has('name'))
                                <div class="text-danger">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-5 mt-5">
                            <label class="col-md-5 text-right col-form-label">Category</label>
                            <div class="col-md-5">
                                <select name="category_id" class="form-control" required>
                                    @foreach ($categories as $categoryTwo)
                                        <option value="{{ $categoryTwo->id }}" {{ !empty($category) ? ($category->category_id == $categoryTwo->id ? 'selected' : '') : '' }}>{{ $categoryTwo->name }}</option>
                                    @endforeach
                                </select>
                                @if($errors->has('category_id'))
                                    <div class="text-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>
                        </div>
                        <input type="hidden" name="type" value="1" />
                        <div class="form-group row mb-5 mt-5">
                            <label class="col-md-5 text-right col-form-label">Position</label>
                            <div class="col-md-5">
                                <input type="number" min="0" name="position" value="{{ !empty(old()) ? old('position') : (isset($category) ? $category->position : '') }}" class="form-control" required />
                                @if($errors->has('category_id'))
                                <div class="text-danger">{{ $errors->first('category_id') }}</div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-5 mb-4">
                    <button class="btn btn-primary px-5">{{ isset($category) ? 'Update' : 'Create' }}</button>
                </div>
            </form>
        </div>
    </div>

</x-app-layout>

resources/views/admin/types/index.blade.php
<x-app-layout>
    <div class="container-fluid" id="app">
        {{-- header --}}
        <div class="row justify-content-between align-items-center w-100 border-bottom pb-4">
            <div class="col-6">
                <h5>Product Types</h5>
            </div>
            <div class="col-6 text-right">
                <a href="{{ route('admin.types.create') }}" class="btn btn-identity px-5">Create</a>
            </div>
        </div>
        {{-- search and button --}}
        <div class="row my-4">
            <div class="col-lg-4 col-md-6">
                <form id="frmSearch" action="{{ route('admin.types.index') }}" method="GET">
                    <div class="w-100">
                        <input type="text" name="q" placeholder="Search in the current filter" value="{{ $query }}" class="form-control d-inline-block" style="width: calc(100% - 100px); background: #ececec">
                        <i class="fa fa-search" onclick="document.getElementById('frmSearch').submit()" style="cursor: pointer;"></i>
                    </div>
                </form>
            </div>
        </div>

        {{-- index table --}}
        <div class="row mt-2">
            <div class="table-responsive">
                <table class="table table-rounded table-striped w-100 mt-4">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Category</th>
                            <th>No. of Products</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->category ? $category->category->name : '-' }}</td>
                                <td>{{ $category->products()->count() }}</td>
                                <td class="d-flex">
                                    <a class="btn-link btn-sm" href="{{ route('admin.types.edit', [$category->getRouteKey()]) }}">Edit</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="text-center bg-white">There are no categories.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        {{ $categories->links() }}
    </div>
</x-app-layout>